import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({ data }: { data: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ backgroundColor: "#fff", height: "100vh", width: "100vw" }}
      >
        <div
          style={{ color: "black" }}
          dangerouslySetInnerHTML={{ __html: data }}
        />
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  return {
    props: {
      data: "<h1>This is h1 heading</h1><br /><b>This is some bold text</b>",
    },
  };
}
